백엔드 초기 세팅
skku-npc/website pull request #8
Opened 2021-01-29 16:04 UTC by threedalpeng

## 변경 사항
- express 초기 세팅
  - 디렉터리 세팅
  - .env 설정
  - prisma ORM 초기 설정
  - .prettierrc.json 설정
- .gitignore 수정
  - .env 주석 처리 (보안 상 위험하지만 배포 시에는 환경 변수가 달라질 것이라 판단)
  - **/migrations 추가 (prisma migrations 폴더)
- README.md 수정
  - 포트 번호 제거

## 백엔드 + prisma 기본 세팅 명령어
```bash
cd backend
yarn install
echo init | yarn prisma migrate dev --preview-feature
yarn prisma db seed --preview-feature
yarn prisma generate
# 이후 개발 시작
```

2021-01-29 21:42 UTC, uniqueimaginate approved these changes
코드 다 확인했습니다.

2021-01-30 05:25 UTC, dotoleeoak commented
Dockerfile 수정본 push 예정입니다

2021-01-30 05:39 UTC, dotoleeoak requested changes

2021-01-30 05:39 UTC, dotoleeoak commented on backend/bin/www
> +server.on('listening', onListening);
`build/index.html`로 routing이 안되는 거 같네요
기존 `index.js` 참고해주세요

2021-01-30 05:39 UTC, dotoleeoak commented on backend/bin/www
> +server.on('listening', onListening);
```js
app.get('/', (req, res) => {
  res.sendFile(path.join(path.resolve(), 'build', 'index.html'));
});
```

2021-01-30 08:55 UTC, threedalpeng commented
Airbnb 코딩 스타일 적용했는데 다시 돌려놓을까요?

2021-01-30 10:18 UTC, dotoleeoak approved these changes

2021-01-30 10:26 UTC, threedalpeng commented
수고하셨습니다

2021-01-30 10:27 UTC, merged